# Generated by Django 5.1.5 on 2025-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.FloatField()),
                ('v2', models.CharField(max_length=10)),
                ('v3', models.FloatField()),
                ('v4', models.FloatField()),
                ('v5', models.FloatField()),
                ('v6', models.FloatField()),
                ('v7', models.FloatField()),
                ('v8', models.FloatField()),
            ],
        ),
    ]
